gnu: python-asdf: Adjust inputs.
python-asdf requires python-semantic-version during runtime which may be
reproduced by:

   guix shell python-asdf python -- python3 -c 'import asdf'
   <...>
   ModuleNotFoundError: No module named 'semantic_version'

* gnu/packages/astronomy.scm (python-asdf): Adjust inputs.
[native-inputs]: Remove python-semantic-version.
[propagated-inputs]: Add python-semantic-version.

(python-asdf-astropy, python-asdf-compression, python-asdf-coordinates-schemas,
python-asdf-wcs-schemas, python-asdf-zarr, python-astroalignn, python-ccdproc,
python-crds, python-ginga, python-gwcs, python-photutils, python-rad,
python-reproject, python-roman-datamodels, python-spectral-cube,
python-specutils, python-stcal, python-stdatamodels, python-stpipe,
python-stsynphot, python-sunpy, python-synphot, python-tweakwcs): Remove
python-semantic-version from native or propagated inputs.

Change-Id: I96bf57f77c327f4ff208e0b173e84bcdd4c287da
Reported-by: Iliya Tikhonenko <tikhonenko@mpe.mpg.de>