gnu: gash: Update to 0.3.1.
Fixes <https://issues.guix.gnu.org/75658>.

Fixes a bug whereby Gash sub-shells would randomly crash, typically when
running ‘configure’ scripts, with:

  ERROR: In procedure fdopen:
  ERROR: In procedure scm_fdes_to_port: Bad file descriptor

The effect is that ‘configure’ would sometimes make wrong guesses,
eventually leading to build failures.

* gnu/packages/shells.scm (gash): Update to 0.3.1.

Change-Id: I5fd48a651601b3c28fbed88dbffaefdef987f1cd