gnu: syncthing-gtk: Update to 0.9.4.4-2.1e84f33.
Fixes the runtime failure:
AttributeError: module 'gettext' has no attribute 'bind_textdomain_codeset'.

* gnu/packages/syncthing.scm (syncthing-gtk): Update to 0.9.4.4-2.1e84f33.

Change-Id: I37d0389a194b6c0d83db859a7cf7e2bdb4f50c54