gnu: python-py3status: Update to 3.50.
This avoids "ImportError: cannot import name 'Iterable' from 'collections'"
from py3status version < 3.25.

* gnu/packages/python-xyz.scm (python-py3status): Update to 3.50.

Signed-off-by: Christopher Baines <mail@cbaines.net>