gnu: gnome-shell-extension-gsconnect: Fix search path prepending.
This patch fixes the following error when attempting to enable GSConnect
in GNOME 49:

> TypeError:
> imports.gi.GIRepository.Repository.prepend_search_path is not a function

‘prepend_search_path’ and other functions are no longer static in GI 2.0,
so a Repository must be instantiated to call them.

* gnu/packages/gnome-xyz.scm (gnome-shell-extension-gsconnect):
[arguments]<#:phases>{patch-gjs-shebangs}: Fix import invocations.

Signed-off-by: Liliana Marie Prikler <liliana.prikler@gmail.com>