gnu: emacs-gerbil-mode: Move to scheme.scm.
This fixes a bug due to a top-level circular reference:

  $ guix show scheme48
  [...]
  ice-9/boot-9.scm:1685:16: In procedure raise-exception:
  error: gerbil: unbound variable

* gnu/packages/emacs-xyz.scm (emacs-gerbil-mode): Move to...
* gnu/packages/scheme.scm (emacs-gerbil-mode): ... here.