gnu: xoscope: Update to 2.3-0.0.0.d97b9b1.
Fixes this build failure:

------
comedi.c: In function ‘open_comedi’:
comedi.c:480:15: error: too few arguments to function ‘comedi_get_cmd_generic_timed’
  480 |         ret = comedi_get_cmd_generic_timed(comedi_dev, comedi_subdevice, &cmd, 0);
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from comedi.c:27:
/gnu/store/hghrvvp0lnmfb8ifad30yfgj1bca7ypx-comedilib-0.13.0/include/comedilib.h:193:5: note: declared here
  193 | int comedi_get_cmd_generic_timed(comedi_t *dev,unsigned int subdevice,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:508: comedi.o] Error 1
------

* gnu/packages/electronics.scm (xoscope): Update to 2.3-0.0.0.d97b9b1.
[origin]: Use git-fetch.
[native-inputs]: Add automake, libtool, autoconf for bootstrapping.

Change-Id: If78a5f4fcdbcf477bc3e7c7dbf57c37ea397c020