tests: vnstat: Avoid call to 'getservbyname'.
This would break "make as-derivation" because /etc/services is
unavailable in the build environment:

  [ 38/ 80] loading...	 95.0% of 40 filesBacktrace:
  In guix/build/compile.scm:
      249:8 19 (compile-files "." "/gnu/store/s5nadqd6hkzivkxp33svwqslfn608ng5-guix-system-tests" ("gnu/tests/audio.scm" "gnu/tests/base.scm" "gnu/tests/ci.scm" "gnu/tests/cups.scm" "gnu/tests/d…" …) …)
  […]
  In unknown file:
	     0 (getserv "discard" "tcp")

  ERROR: In procedure getserv:
  In procedure getserv: no such service discard
  builder for `/gnu/store/…-guix-system-tests.drv' failed with exit code 1

* gnu/tests/vnstat.scm (run-vnstat-test): Hard-code 'guest-port' instead
of calling 'getservbyname'.