gnu: linux-libre-documentation: Fix compilation.
When compiling linux-libre-documentation@6.6.16, the compilation fails with
following error message:

------
    Exception occurred:
      File "/tmp/guix-build-linux-libre-documentation-6.6.16.drv-0/linux-6.6.16/Documentation/sphinx/kernel_feat.py", line 112, in run
        nodeList = self.nestedParse(out_lines, fname)
    UnboundLocalError: local variable 'fname' referenced before assignment
------

This is already fixed upstream[0], so this commit backports the change.

0: https://lore.kernel.org/all/20240206054907.066a0325@coco.lan/t/

* gnu/packages/linux.scm (linux-libre-documentation): Apply patch fixing
compilation.

Change-Id: Ic96f14aa25df09f38e029ca70d2647cbf37c2365
Signed-off-by: Leo Famulari <leo@famulari.name>