gnu: trilinos-for-dealii-openmpi: Fix build.
This fixes the error

  error: ‘std::hypot’ has not been declared

caused by using an older version of gcc, but requires some patches to
placate newer versions of gcc.

* gnu/packages/maths.scm (trilinos-for-dealii-openmpi)[origin]: Add
patches.
[native-inputs]: Remove gcc-7.
* gnu/packages/patches/teuchos-remove-duplicate-using.patch: New file.
* gnu/packages/patches/tpetra-remove-duplicate-using.patch: Likewise.
* gnu/local.mk (dist_patch_DATA): Register them.

Signed-off-by: Ludovic Courtès <ludo@gnu.org>