gnu: dde-sources: Update to 066797b576.
This fixes the build with reinforced build options:

    condvar.c: In function ‘ddekit_condvar_init’:
    condvar.c:16:19: error: old-style function definition [-Werror=old-style-definition]
       16 | ddekit_condvar_t *ddekit_condvar_init() {
          |                   ^~~~~~~~~~~~~~~~~~~

* gnu/packages/hurd.scm (dde-sources): Update to
066797b576ebf8364ad157f50bef2a655597deeb.

Change-Id: Icf6f97897852e21dfcf9b77629fde4ce6a7d1469